[package]
name = "custom-framework-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "custom_framework_rust"
path = "src/lib.rs"

[dependencies]
once_cell = "1.17.0"
wasmedge-sdk = "0.7.1"
