/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom_framework_example;

import custom_framework.Server;

public class App {
    public static void main(String[] args) {
        Server server = new Server();
        server.start();
    }
}
