/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom_framework;

import org.junit.Test;

public class ServerTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        Server classUnderTest = new Server();
        classUnderTest.addRoute(new RouteHandler("/", (request) -> "Hello World!"));
        classUnderTest.start();
    }
}
