/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom_framework;

import java.util.List;

import org.wasmedge.ConfigureContext;
import org.wasmedge.StoreContext;
import org.wasmedge.WasmEdge;
import org.wasmedge.WasmEdgeVm;
import org.wasmedge.enums.HostRegistration;

public class App {
    public static void main(String[] args) {
        // Init wasmedge
        WasmEdge.init();
        ConfigureContext config = new ConfigureContext();
        config.addHostRegistration(
                HostRegistration.WasmEdge_HostRegistration_Wasi);
        StoreContext store = new StoreContext();
        // Create WasmEdgeVM
        WasmEdgeVm vm = new WasmEdgeVm(config, store);
        vm.registerModuleFromFile("custom_framework", "libs/custom_framework_wasm.wasm");
        vm.executeRegistered("custom_framework", "start", List.of(), List.of());
    }
}
