/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom_framework;

public class Server {
    ModuleWrapper frameworkModule;

    public Server() {
        this.frameworkModule = new ModuleWrapper();
    }

    public void start() {
        this.frameworkModule.start();
    }

}
