/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package custom_framework;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import org.wasmedge.ConfigureContext;
import org.wasmedge.StoreContext;
import org.wasmedge.WasmEdge;
import org.wasmedge.WasmEdgeVm;
import org.wasmedge.enums.HostRegistration;

public class Server {
    WasmEdgeVm vm;

    public Server() {
        String WASM_BINARY_PATH = "/custom_framework_wasm.wasm";

        try (InputStream in = getClass().getResourceAsStream(WASM_BINARY_PATH)) {

            byte[] bytesArray = in.readAllBytes();
            WasmEdge.init();
            ConfigureContext config = new ConfigureContext();
            config.addHostRegistration(
                    HostRegistration.WasmEdge_HostRegistration_Wasi);
            StoreContext store = new StoreContext();
            this.vm = new WasmEdgeVm(config, store);
            this.vm.registerModuleFromBuffer("custom_framework", bytesArray);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void start() {
        this.vm.executeRegistered("custom_framework", "start", List.of(), List.of());
    }
}
